### ISSUE TITLE
Support for Building / Writing

### ISSUE THREAD

**Issue by cornytrace** [stephen-bunn/bethesda-structs#15]
As a hobby project, i'm trying to write a python script to automate some transformations on esm / esp files. Your library looks excellent, however after a bit of reading I figured out that there is no write support (or build support in construct terms). I figured I could do something like `plugin.plugin_struct.build_file(plugin.container, "Test.esm")`. This does produce a valid file, and if you change something like plugin.container.header.version it does show in Test.esm. However, if something in a subrecord is changed (e.g. the CNAM author name in the header), this does not propagate to Test.esm.
What changes would be necessary to enable writing esm's?
Is this a feature you are planning / would be willing to implement?

**Comment by stephen-bunn** [comment]
Unfortunately no, I don't have immediate plans to build anything to handle writing Bethesda plugins. Even performing basic extraction is extremely tedious and error-prone. Construct does provide methods of writing the structures back out, however, when I played around with that functionality **many obscure bugs** within the creation engine came out from under the fridge. 🐞

If you haven't noticed this library is vastly lacking in the types of subrecord structures it can extract (and currently I only have the basics in FNV working [see #2 for more info on what subrecords have been handled so far]).

**Primarily the benefit this library currently provides is the extraction of Bethesda's archive formats (`.bsa` and `.ba2`).** The only instance where I would use this package in regard to plugins would be to extract the masters necessary for proper `.es{p,m,l}` dependency resolution.

--- 

I honestly wish that Bethesda would just publish the file structures they utilize for the creation engine and I wouldn't have to rely 100% on myself other **amazing** contributors shoddily reverse-engineering the structures ourselves. However, with the release of Fallout 76 being a network-enabled version of the creation engine using the same ol' structure, it is very unlikely they would ever publish any documentation on them.

I've been out of the game with handling Bethesda file formats for a while. It's become too tedious for me and other projects and work has made this project become slightly stale.
